version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    ports:
      - ${PG_PORT}:${PG_PORT}
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src